name: MCI Direct Publisher

on:
  schedule:
    # اجرا در دقیقه ۱۷ هر ساعت (خارج از ترافیک سنگین سرورهای گیت‌هاب)
    - cron: '17 * * * *'
  workflow_dispatch: # امکان اجرای دستی با دکمه برای تست

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Direct Publisher
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SOURCE_MCI: ${{ secrets.SOURCE_MCI }}
        run: |
          python main.py
